name: CD - Deploy Lambda From ECR Image

on:
  workflow_run:
    workflows: [ "CI - Build and Push Image" ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Lambda to new image
        run: |
          aws lambda update-function-code \
            --function-name audit_event_handler \
            --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/datagrokr-intern-devops:latest

      - name: Verify Deployment (Invoke)
        run: |
          aws lambda invoke \
            --function-name audit_event_handler \
            --payload '{}' \
            response.json
          cat response.json
